remote theme: minimal-mistakes-jekyll
title: [Jasmine Brewer]
name: "Jasmine Brewer"
logo: /jasmine.png
description: [Jasmine Brewer's homepage]
author:
  name     : "Your Name"
  avatar   : "/jasmine.jpg"
  bio      : "My awesome biography constrained to a sentence or two goes here."
  location : "Somewhere, USA"
plugins:
  - jekyll-include-cache