theme: minimal-mistakes-jekyll
title: [Jasmine Brewer]
logo: /jasmine.jpg
description: [Jasmine Brewer's homepage]
layout: single
toc: true
author:
  name     : "Your Name"
  avatar   : "/jasmine.jpg"
  bio      : "My awesome biography constrained to a sentence or two goes here."
  location : "Somewhere, USA"
plugins:
  - jekyll-include-cache